### ISSUE TITLE
Redering lib

### ISSUE THREAD

**Issue by cfilipov** [livechat/octopus#11]
I love this project! I very much want to echo what was said in #5.

Question about the use of markdown rendering lib. I notice this project uses [remarkable](https://github.com/jonschlinkert/remarkable). I was looking to extend it with plugins for my internal wiki, then I found [markdown-it](https://github.com/markdown-it/markdown-it). Confusingly these two projects have nearly identical APIs, documentation and demo pages. After some digging around it seems there's some drama between the authors of the aforementioned libraries and they do indeed share a common history. I don't care to learn more about their beef, what I'm trying to understand is why one would choose one lib over the other. What are their technical differences, how did they diverge? Why did you go with remarkable vs markdown-it?

**Comment by cfilipov** [comment]
Some difference I was able to gather so far:

| Remarkable | Markdown-it |
| ----------- | --------------|
| Uses ES6 classes/`new` | ES5-style |
| | [Used by VSCode](https://github.com/Microsoft/vscode/issues/4668) |
| | [Way more plugins](https://www.npmjs.com/browse/keyword/markdown-it-plugin) |

**Comment by bolchowka** [comment]
There was no specific reason for using remarkable over markdown-it. I just picked the first library that was working as I expected and that's it.
