### ISSUE TITLE
installed failed , 'firebase' is not in the npm registry

### ISSUE THREAD

**Issue by changchichung** [livechat/octopus#12]
sorry , i have trouble doing " npm install "
OS: ubuntu 14.04 Desktop

``
npm install
npm http GET https://registry.npmjs.org/firebase/app/0.1.10
npm http GET https://registry.npmjs.org/firebase/auth/0.4.0
npm http GET https://registry.npmjs.org/firebase/database/0.2.1
npm http GET https://registry.npmjs.org/firebase/firestore/0.3.6
npm http GET https://registry.npmjs.org/firebase/functions/0.1.0
npm http GET https://registry.npmjs.org/firebase/messaging/0.2.2
npm http GET https://registry.npmjs.org/firebase/polyfill/0.3.0
npm http GET https://registry.npmjs.org/firebase/storage/0.1.8
npm http GET https://registry.npmjs.org/dom-storage
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http 404 https://registry.npmjs.org/firebase/app/0.1.10
npm http 404 https://registry.npmjs.org/firebase/firestore/0.3.6
npm http 404 https://registry.npmjs.org/firebase/database/0.2.1
npm ERR! 404 'firebase' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.0-111-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/changch/Documents/octopus
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 404 https://registry.npmjs.org/firebase/functions/0.1.0
npm http 404 https://registry.npmjs.org/firebase/auth/0.4.0
npm http 304 https://registry.npmjs.org/dom-storage
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http 404 https://registry.npmjs.org/firebase/polyfill/0.3.0
npm http 404 https://registry.npmjs.org/firebase/messaging/0.2.2
npm http 404 https://registry.npmjs.org/firebase/storage/0.1.8
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/changch/Documents/octopus/npm-debug.log
npm ERR! not ok code 0
``
any suggestions ?

**Comment by quarties** [comment]
hello @changchichung - sorry for late reply :-(

Do you still experience this issue? What is your node version?

**Comment by quarties** [comment]
@changchichung I'm closing this issue for now - let us know if it doesn't work after updating your node
