### ISSUE TITLE
"Access denied for" error message

### ISSUE THREAD

**Issue by Masterkriz** [livechat/octopus#17]
Hi,

I am trying to set this up in my server but after following the guide I keep getting the following error message: 
"Access denied for [google account placeholder]"
"Sign out"

When I click on 'Sign out' then it makes a connection to Firebase and then proceeds to show the same page. Any ideas what might cause this?

Thanks.

**Comment by kamil-rudnicki** [comment]
We had the same issue. We forgot to switch `Real time database` instead of `Cloud Firestore` when changing permissions.
