### ISSUE TITLE
MADLY IN LOVE

### ISSUE THREAD

**Issue by sebastianarena** [livechat/octopus#5]
We just wanted to reach out to you guys, saying that we just LOVE this project.
By a huge coincidence, a day before this release we decided to put a wiki in our organization.
I struggled finding the right choice, and this was just the best out there.

Much appreciation.

It took a little tweaking to set it up with our branding and other small things. But overall the setup was great. Would love to contribute in the future, to make it easier to clone the project, setup and deploy.

There are a couple of things we tried making work, and we couldn't. We reach out to you if you find the good to include:

- Table of contents, by the same people of remarkable. For some reason, webpack doesn't like the plugin. https://github.com/jonschlinkert/markdown-toc
- Italics? Seems weird enough, but it seems italics don't work with Markdown for some reason

THANK YOU!!

**Comment by bolchowka** [comment]
Thanks, Sebastian! I'm glad you found this project helpful.

I wish Octopus had more such "issues" :) Will keep this one open for a while!
